steps:
  - name: gcr.io/cloud-builders/mvn
    args: ["--batch-mode", "package", "-P", "kafka-0-11"]

  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "us.gcr.io/${PROJECT_ID}/secor:${COMMIT_SHA}"
      - "-t"
      - "us.gcr.io/${PROJECT_ID}/secor:latest"
      - "."

images:
  - "us.gcr.io/${PROJECT_ID}/secor:${COMMIT_SHA}"
  - "us.gcr.io/${PROJECT_ID}/secor:latest"
