steps:
  - name: maven:3-jdk-8
    args: [
      "mvn",
      "--batch-mode",
      "package",
    ]

  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "--cache-from"
      - "us.gcr.io/${PROJECT_ID}/secor:latest"
      - "-t"
      - "us.gcr.io/${PROJECT_ID}/secor:${COMMIT_SHA}"
      - "-t"
      - "us.gcr.io/${PROJECT_ID}/secor:latest"
      - "."

timeout: 1200s
images:
  - "us.gcr.io/${PROJECT_ID}/secor"
