FROM maven:3-jdk-8

COPY cloudbuild-m2settings.xml /usr/share/maven/ref/settings.xml
COPY pom.xml /tmp/pom.xml
RUN mvn -B -f /tmp/pom.xml -s /usr/share/maven/ref/settings-docker.xml org.apache.maven.plugins:maven-dependency-plugin:3.1.1:go-offline org.apache.maven.plugins:maven-dependency-plugin:3.1.1:resolve-plugins
WORKDIR /workspace/
COPY . .
# Annotates build-reversion from .git
COPY .git .git 
RUN mvn --batch-mode -s /usr/share/maven/ref/settings-docker.xml clean package -P kafka-0-11 
